package com.poorknight.testing.matchers.utils.testclasses;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


public class ClassWithAutoGeneratedAutoGeneratedIDAttributeWithWrongStrategy {

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private Long pk;

}
