CREATE TABLE C01_RECIPE (
  C01_RECIPE_ID int(11) NOT NULL AUTO_INCREMENT,
  C01_RECIPE_NAME varchar(1024) NOT NULL,
  C01_RECIPE_CONTENT text NOT NULL,
  C01_CREATED_ON timestamp NULL DEFAULT NULL,
  C01_CREATED_BY varchar(255) DEFAULT NULL,
  C01_LAST_UPDATED_ON timestamp NULL DEFAULT NULL,
  C01_LAST_UPDATED_BY varchar(255) DEFAULT NULL,
  PRIMARY KEY (C01_RECIPE_ID),
  UNIQUE KEY C01_RECIPE_ID_UNIQUE (C01_RECIPE_ID))
  